[build]
  command = "npm run build"
  publish = "dist"

[dev]
  port = 3007
  targetPort = 5174
  framework = "#auto"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[context.deploy-preview]
  ignore = "exit 1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
