// Runs one LLM stage headlessly: node stage.mjs <name>
// Reads prompts/<name>.md + schemas/<name>.json, fills {{placeholders}} from the run's files,
// calls `claude -p` with a tight tool allowlist and a budget cap, and saves structured output
// to runs/<date>/<name>.json. Cost is appended to runs/<date>/cost.jsonl.
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import yaml from 'js-yaml';
import { HERE, REPO, STATE, loadYaml, readJson, writeJson, runDir } from './lib.mjs';

const name = process.argv[2];
if (!name) { console.error('usage: node stage.mjs <stage>'); process.exit(2); }

const config = loadYaml('config.yaml');
const stage = config.stages[name];
if (!stage) { console.error(`no stage "${name}" in config.yaml`); process.exit(2); }

const dir = runDir();
const fill = {
  date: path.basename(dir),
  collected: () => JSON.stringify(compactCollected(readJson(path.join(dir, 'collected.json'), { items: [] })), null, 1),
  health: () => JSON.stringify(readJson(path.join(dir, 'health.json'), {}), null, 1),
  topicMap: () => fs.existsSync(path.join(HERE, 'topic-map.yaml')) ? fs.readFileSync(path.join(HERE, 'topic-map.yaml'), 'utf8') : '(no topic map yet)',
  feedback: () => {
    const p = path.join(STATE, 'feedback.jsonl');
    return fs.existsSync(p) ? fs.readFileSync(p, 'utf8').trim().split('\n').slice(-40).join('\n') : '(no feedback yet)';
  },
  lessonList: () => JSON.stringify(readJson(path.join(dir, 'health.json'), { lessons: [] }).lessons.map((l) => l.file)),
};

function compactCollected(c) {
  return c.items.slice(0, config.maxItemsForTriage).map(({ source, weight, title, link, date, summary }) =>
    ({ source, weight, title, link, date: date?.slice(0, 10), summary: summary?.slice(0, 600) }));
}

let prompt = fs.readFileSync(path.join(HERE, 'prompts', `${name}.md`), 'utf8');
prompt = prompt.replace(/\{\{(\w+)\}\}/g, (_, k) => {
  const v = fill[k];
  if (v === undefined) throw new Error(`unknown placeholder {{${k}}} in prompts/${name}.md`);
  return typeof v === 'function' ? v() : v;
});

const schema = fs.readFileSync(path.join(HERE, 'schemas', `${name}.json`), 'utf8');
const args = [
  '-p',
  '--output-format', 'json',
  '--no-session-persistence',
  '--json-schema', schema,
  '--allowedTools', ...stage.tools,
  '--disallowedTools', 'Bash', 'Edit', 'Write', 'NotebookEdit',
  '--max-budget-usd', String(stage.maxBudgetUsd ?? config.limits.maxBudgetUsdPerStage),
];
if (stage.model) args.push('--model', stage.model);

const started = Date.now();
const res = spawnSync('claude', args, { cwd: REPO, input: prompt, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024, timeout: (stage.timeoutMin ?? 20) * 60e3 });
const secs = Math.round((Date.now() - started) / 1000);

let out;
try { out = JSON.parse(res.stdout); } catch {
  console.error(`${name}: claude returned no JSON (exit ${res.status}, ${secs}s)`);
  console.error((res.stderr || res.stdout || '').slice(-2000));
  process.exit(1);
}
fs.appendFileSync(path.join(dir, 'cost.jsonl'), JSON.stringify({ stage: name, usd: out.total_cost_usd, secs, turns: out.num_turns, error: out.is_error }) + '\n');

if (out.is_error || !out.structured_output) {
  console.error(`${name}: failed (${out.subtype || out.terminal_reason || 'no structured output'}), $${out.total_cost_usd?.toFixed(2)}`);
  console.error(String(out.result || '').slice(-2000));
  process.exit(1);
}

writeJson(path.join(dir, `${name}.json`), out.structured_output);
if (stage.writeYaml) fs.writeFileSync(path.join(HERE, stage.writeYaml), `# Generated by ops/autopilot (stage: ${name}) on ${fill.date}. Edit freely; the next run reads it.\n` + yaml.dump(out.structured_output, { lineWidth: 120 }));
console.log(`${name}: ok in ${secs}s, ${out.num_turns} turns, $${out.total_cost_usd?.toFixed(2)}`);
