// Runs one LLM stage headlessly.
//   CLI:    node stage.mjs <name>            (topic-map, brief)
//   Module: runStage(name, { cwd, vars, tools, outPath })   (draft, audit: one call per change)
// Reads prompts/<name>.md + schemas/<name>.json, fills {{placeholders}}, calls `claude -p` with a
// tool allowlist and a budget cap, and returns the structured output. Cost goes to runs/<date>/cost.jsonl.
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import yaml from 'js-yaml';
import { HERE, REPO, STATE, loadYaml, readJson, writeJson, runDir } from './lib.mjs';

const config = loadYaml('config.yaml');

function compactCollected(c) {
  return c.items.slice(0, config.maxItemsForTriage).map(({ source, weight, title, link, date, summary }) =>
    ({ source, weight, title, link, date: date?.slice(0, 10), summary: summary?.slice(0, 600) }));
}

// Placeholders every prompt can use; per-call `vars` add to or override these.
function defaultVars(dir) {
  return {
    date: path.basename(dir),
    collected: () => JSON.stringify(compactCollected(readJson(path.join(dir, 'collected.json'), { items: [] })), null, 1),
    health: () => JSON.stringify(readJson(path.join(dir, 'health.json'), {}), null, 1),
    topicMap: () => fs.existsSync(path.join(HERE, 'topic-map.yaml')) ? fs.readFileSync(path.join(HERE, 'topic-map.yaml'), 'utf8') : '(no topic map yet)',
    feedback: () => {
      const p = path.join(STATE, 'feedback.jsonl');
      return fs.existsSync(p) ? fs.readFileSync(p, 'utf8').trim().split('\n').slice(-40).join('\n') : '(no feedback yet)';
    },
    pending: () => JSON.stringify(readJson(path.join(dir, 'pending.json'), []), null, 1),
    learners: () => {
      const l = readJson(path.join(dir, 'learners.json'), null);
      return l ? JSON.stringify(l, null, 1) : '(no learner data available)';
    },
    lessonList: () => JSON.stringify(readJson(path.join(dir, 'health.json'), { lessons: [] }).lessons.map((l) => l.file)),
  };
}

export function runStage(name, { cwd = REPO, vars = {}, tools, outPath } = {}) {
  const stage = config.stages[name];
  if (!stage) throw new Error(`no stage "${name}" in config.yaml`);
  const dir = runDir();
  const all = { ...defaultVars(dir), ...vars };

  const prompt = fs.readFileSync(path.join(HERE, 'prompts', `${name}.md`), 'utf8').replace(/\{\{(\w+)\}\}/g, (_, k) => {
    const v = all[k];
    if (v === undefined) throw new Error(`unknown placeholder {{${k}}} in prompts/${name}.md`);
    return typeof v === 'function' ? v() : v;
  });

  const args = [
    '-p',
    '--output-format', 'json',
    '--no-session-persistence',
    '--json-schema', fs.readFileSync(path.join(HERE, 'schemas', `${name}.json`), 'utf8'),
    '--allowedTools', ...(tools || stage.tools),
    '--disallowedTools', 'Bash', 'NotebookEdit', ...(stage.denyWrites === false ? [] : ['Edit', 'Write']),
    '--max-budget-usd', String(stage.maxBudgetUsd ?? config.limits.maxBudgetUsdPerStage),
  ];
  if (stage.model) args.push('--model', stage.model);

  const started = Date.now();
  const res = spawnSync('claude', args, { cwd, input: prompt, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024, timeout: (stage.timeoutMin ?? 20) * 60e3 });
  const secs = Math.round((Date.now() - started) / 1000);

  let out;
  try { out = JSON.parse(res.stdout); } catch {
    throw new Error(`${name}: claude returned no JSON (exit ${res.status}, ${secs}s): ${(res.stderr || res.stdout || '').slice(-1500)}`);
  }
  fs.appendFileSync(path.join(dir, 'cost.jsonl'), JSON.stringify({ stage: name, usd: out.total_cost_usd, secs, turns: out.num_turns, error: out.is_error }) + '\n');
  if (out.is_error || !out.structured_output) {
    throw new Error(`${name}: failed (${out.subtype || out.terminal_reason || 'no structured output'}), $${out.total_cost_usd?.toFixed(2)}: ${String(out.result || '').slice(-1500)}`);
  }

  if (outPath !== null) writeJson(outPath || path.join(dir, `${name}.json`), out.structured_output);
  if (stage.writeYaml) fs.writeFileSync(path.join(HERE, stage.writeYaml), `# Generated by ops/autopilot (stage: ${name}) on ${all.date}. Edit freely; the next run reads it.\n` + yaml.dump(out.structured_output, { lineWidth: 120 }));
  console.log(`${name}: ok in ${secs}s, ${out.num_turns} turns, $${out.total_cost_usd?.toFixed(2)}`);
  return out.structured_output;
}

// CLI
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const name = process.argv[2];
  if (!name) { console.error('usage: node stage.mjs <stage>'); process.exit(2); }
  try { runStage(name); } catch (e) { console.error(e.message); process.exit(1); }
}
