// ============================================
// OPEN VECTOR — EXTERNAL RESOURCES CATALOG
// ============================================
// Harvested from lesson "Go Deeper" sections + curated additions.
// Each resource is tagged by type and topic for filtering.

export const resourceTypes = [
  { key: 'all', label: 'All' },
  { key: 'book', label: 'Books' },
  { key: 'article', label: 'Articles' },
  { key: 'course', label: 'Courses' },
  { key: 'tool', label: 'Tools' },
  { key: 'reference', label: 'Reference' },
];

export const topicFilters = [
  { key: 'all', label: 'All Topics' },
  { key: 'fundamentals', label: 'Fundamentals', glyph: '\u00A7' },
  { key: 'architecture', label: 'Architecture', glyph: '\u2302' },
  { key: 'ai', label: 'AI & Tools', glyph: '\u00B6' },
  { key: 'web', label: 'Web Dev', glyph: '\u2039' },
  { key: 'deployment', label: 'Deployment', glyph: '\u2191' },
  { key: 'research', label: 'Research', glyph: '\u2020' },
  { key: 'process', label: 'Process', glyph: '\u2261' },
  { key: 'leadership', label: 'Leadership', glyph: '\u03A9' },
  { key: 'craft', label: 'Craft', glyph: '\u2666' },
  { key: 'community', label: 'Community', glyph: '\u2665' },
];

const resources = [
  // ── Books ─────────────────────────────────────────────
  {
    title: 'Pro Git',
    author: 'Scott Chacon & Ben Straub',
    url: 'https://git-scm.com/book/en/v2',
    description: 'The complete guide to Git. Free, thorough, and the definitive reference.',
    type: 'book',
    topics: ['fundamentals'],
  },
  {
    title: 'Thinking in Systems',
    author: 'Donella Meadows',
    url: 'https://www.chelseagreen.com/product/thinking-in-systems/',
    description: 'The primer on systems thinking. Short, clear, and permanently changes how you see the world.',
    type: 'book',
    topics: ['architecture'],
  },
  {
    title: 'A Philosophy of Software Design',
    author: 'John Ousterhout',
    url: 'https://web.stanford.edu/~ouster/cgi-bin/book.php',
    description: 'How to reduce software complexity. The best book on writing clean systems.',
    type: 'book',
    topics: ['architecture'],
  },
  {
    title: 'Shape Up',
    author: 'Basecamp',
    url: 'https://basecamp.com/shapeup',
    description: 'Product development methodology for small teams. Free. Opinionated and practical.',
    type: 'book',
    topics: ['process'],
  },
  {
    title: 'The Mythical Man-Month',
    author: 'Fred Brooks',
    url: 'https://en.wikipedia.org/wiki/The_Mythical_Man-Month',
    description: 'Classic essays on software project management. "Adding people to a late project makes it later."',
    type: 'book',
    topics: ['leadership'],
  },
  {
    title: 'Getting Real',
    author: 'Basecamp',
    url: 'https://basecamp.com/gettingreal',
    description: 'Building web apps with less. Free. A manifesto for shipping small and fast.',
    type: 'book',
    topics: ['process'],
  },
  {
    title: 'Database Design for Mere Mortals',
    author: 'Michael J. Hernandez',
    url: 'https://www.oreilly.com/library/view/database-design-for/9780136788041/',
    description: 'Practical, accessible guide to relational database design.',
    type: 'book',
    topics: ['architecture'],
  },
  {
    title: 'Information Architecture (4th Edition)',
    author: 'Rosenfeld, Morville & Arango',
    url: 'https://www.oreilly.com/library/view/information-architecture-4th/9781491911686/',
    description: 'The definitive reference on organizing information for the web.',
    type: 'book',
    topics: ['architecture'],
  },
  {
    title: 'How to Make Sense of Any Mess',
    author: 'Abby Covert',
    url: 'https://www.howtomakesenseofanymess.com/',
    description: 'Information architecture for everyone. Short, visual, and immediately applicable.',
    type: 'book',
    topics: ['architecture', 'research'],
  },
  {
    title: 'The Design of Everyday Things',
    author: 'Don Norman',
    url: 'https://www.nngroup.com/books/design-everyday-things-revised/',
    description: 'Foundational design principles. Why doors confuse you and what that means for software.',
    type: 'book',
    topics: ['craft'],
  },
  {
    title: 'Ship It!',
    author: 'Jared Richardson & Will Gwaltney',
    url: 'https://pragprog.com/titles/prj/ship-it/',
    description: 'Practical, no-nonsense guide to shipping software.',
    type: 'book',
    topics: ['process'],
  },
  {
    title: 'Just Enough Research',
    author: 'Erika Hall',
    url: 'https://abookapart.com/products/just-enough-research',
    description: 'How to do meaningful design research without getting lost. Sharp and funny.',
    type: 'book',
    topics: ['research'],
  },
  {
    title: 'The Mom Test',
    author: 'Rob Fitzpatrick',
    url: 'https://www.momtestbook.com/',
    description: 'How to talk to customers without them lying to you. Essential for anyone building products.',
    type: 'book',
    topics: ['research'],
  },
  {
    title: 'Competing Against Luck',
    author: 'Clayton Christensen',
    url: 'https://www.hbs.edu/faculty/Pages/item.aspx?num=51207',
    description: 'The Jobs to Be Done framework from the person who coined it.',
    type: 'book',
    topics: ['research'],
  },
  {
    title: 'Intercom on Jobs to Be Done',
    author: 'Intercom',
    url: 'https://www.intercom.com/resources/books/intercom-jobs-to-be-done',
    description: 'Practical, product-focused take on JTBD. Free download.',
    type: 'book',
    topics: ['research'],
  },
  {
    title: 'Sprint',
    author: 'Jake Knapp',
    url: 'https://www.thesprintbook.com/',
    description: 'The five-day design sprint process from Google Ventures.',
    type: 'book',
    topics: ['process', 'research'],
  },
  {
    title: 'Creative Confidence',
    author: 'Tom & David Kelley',
    url: 'https://www.creativeconfidence.com/',
    description: 'Unleashing creative potential in yourself and your team. From the founders of IDEO.',
    type: 'book',
    topics: ['craft'],
  },
  {
    title: 'The Lean Startup',
    author: 'Eric Ries',
    url: 'http://theleanstartup.com/',
    description: 'Build-Measure-Learn methodology. The framework behind modern product development.',
    type: 'book',
    topics: ['process'],
  },
  {
    title: 'Rocket Surgery Made Easy',
    author: 'Steve Krug',
    url: 'https://www.sensible.com/rocket-surgery-made-easy/',
    description: 'DIY usability testing. Do it yourself, this week, with no budget.',
    type: 'book',
    topics: ['research'],
  },
  {
    title: "Don't Make Me Think",
    author: 'Steve Krug',
    url: 'https://www.sensible.com/dont-make-me-think/',
    description: 'The classic on web usability. Short, funny, still relevant after 20 years.',
    type: 'book',
    topics: ['craft'],
  },
  {
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    url: 'https://dataintensive.net/',
    description: 'Modern distributed systems design. Dense but rewarding.',
    type: 'book',
    topics: ['architecture'],
  },
  {
    title: 'Staff Engineer',
    author: 'Will Larson',
    url: 'https://staffeng.com/book',
    description: 'What happens after senior engineer. Leadership through technical excellence.',
    type: 'book',
    topics: ['leadership'],
  },
  {
    title: 'The Checklist Manifesto',
    author: 'Atul Gawande',
    url: 'https://atulgawande.com/book/the-checklist-manifesto/',
    description: 'How simple checklists prevent catastrophic failures. Applicable everywhere.',
    type: 'book',
    topics: ['leadership'],
  },
  {
    title: 'Accelerate',
    author: 'Forsgren, Humble & Kim',
    url: 'https://itrevolution.com/product/accelerate/',
    description: 'The science of DevOps. Data-driven proof that speed and quality are not tradeoffs.',
    type: 'book',
    topics: ['leadership'],
  },
  {
    title: 'Team Topologies',
    author: 'Skelton & Pais',
    url: 'https://teamtopologies.com/',
    description: 'Organizing teams for fast flow of change. Essential for multi-agent thinking.',
    type: 'book',
    topics: ['leadership'],
  },
  {
    title: "The Manager's Path",
    author: 'Camille Fournier',
    url: 'https://www.oreilly.com/library/view/the-managers-path/9781491973882/',
    description: 'Engineering management at every level. Read this even if you never manage people.',
    type: 'book',
    topics: ['leadership'],
  },
  {
    title: 'The Practice',
    author: 'Seth Godin',
    url: 'https://seths.blog/thepractice/',
    description: 'Shipping creative work consistently. The antidote to waiting for inspiration.',
    type: 'book',
    topics: ['craft'],
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    url: 'https://jamesclear.com/atomic-habits',
    description: 'Building and breaking habits through tiny changes. Systems over goals.',
    type: 'book',
    topics: ['craft'],
  },
  {
    title: 'Design Systems',
    author: 'Alla Kholmatova',
    url: 'https://www.smashingmagazine.com/design-systems-book/',
    description: 'Creating effective, evolving design systems. From Smashing Magazine.',
    type: 'book',
    topics: ['architecture', 'craft'],
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'Hunt & Thomas',
    url: 'https://pragprog.com/titles/tpp20/',
    description: 'Foundational software craftsmanship. Timeless principles for building well.',
    type: 'book',
    topics: ['craft'],
  },
  {
    title: 'Show Your Work',
    author: 'Austin Kleon',
    url: 'https://austinkleon.com/show-your-work/',
    description: 'Sharing your creative process publicly. Short, visual, and motivating.',
    type: 'book',
    topics: ['community'],
  },
  {
    title: 'Teaching Tech Together',
    author: 'Greg Wilson',
    url: 'https://teachtogether.tech/',
    description: 'Evidence-based teaching for programming. Free online.',
    type: 'book',
    topics: ['community'],
  },
  {
    title: 'Working in Public',
    author: 'Nadia Asparouhova',
    url: 'https://press.stripe.com/working-in-public',
    description: 'The making and maintenance of open source software. Fascinating and honest.',
    type: 'book',
    topics: ['community'],
  },
  {
    title: 'The Cathedral and the Bazaar',
    author: 'Eric Raymond',
    url: 'http://www.catb.org/~esr/writings/cathedral-bazaar/',
    description: 'Open source development models. The essay that helped launch a movement.',
    type: 'book',
    topics: ['community'],
  },
  {
    title: 'Get Together',
    author: 'Richardson, Huynh & Sotto',
    url: 'https://www.gettogether.world/',
    description: 'How to build community. Practical stories and frameworks.',
    type: 'book',
    topics: ['community'],
  },
  {
    title: 'The Art of Gathering',
    author: 'Priya Parker',
    url: 'https://www.priyaparker.com/the-art-of-gathering',
    description: 'Creating meaningful gatherings. Transforms how you think about bringing people together.',
    type: 'book',
    topics: ['community'],
  },
  {
    title: 'Steal Like an Artist',
    author: 'Austin Kleon',
    url: 'https://austinkleon.com/steal/',
    description: 'Creative inspiration and influence. Nothing is original — and that is liberating.',
    type: 'book',
    topics: ['craft'],
  },
  {
    title: 'The War of Art',
    author: 'Steven Pressfield',
    url: 'https://stevenpressfield.com/books/the-war-of-art/',
    description: 'Overcoming creative resistance. Short, fierce, and necessary.',
    type: 'book',
    topics: ['craft'],
  },
  {
    title: 'Refactoring UI',
    author: 'Adam Wathan & Steve Schoger',
    url: 'https://www.refactoringui.com/',
    description: 'Practical UI design tactics for developers. Before and after examples.',
    type: 'book',
    topics: ['craft', 'web'],
  },
  {
    title: 'Domain-Driven Design Quickly',
    author: 'InfoQ',
    url: 'https://www.infoq.com/minibooks/domain-driven-design-quickly/',
    description: 'Quick introduction to Domain-Driven Design concepts. Free.',
    type: 'book',
    topics: ['architecture'],
  },

  // ── Courses ───────────────────────────────────────────
  {
    title: 'The Missing Semester of Your CS Education',
    author: 'MIT',
    url: 'https://missing.csail.mit.edu/',
    description: 'The tools and skills nobody teaches in CS. Shell, Git, editors, debugging. Start here.',
    type: 'course',
    topics: ['fundamentals'],
  },
  {
    title: 'Command Line Power User',
    author: 'Wes Bos',
    url: 'https://commandlinepoweruser.com/',
    description: 'Free terminal video series. Quick, practical, well-produced.',
    type: 'course',
    topics: ['fundamentals'],
  },
  {
    title: 'Prompt Engineering for Developers',
    author: 'DeepLearning.AI',
    url: 'https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/',
    description: 'Structured prompt engineering from Andrew Ng. Free short course.',
    type: 'course',
    topics: ['ai'],
  },
  {
    title: 'GitHub Skills',
    author: 'GitHub',
    url: 'https://skills.github.com/',
    description: 'Interactive, hands-on GitHub learning paths. Learn by doing.',
    type: 'course',
    topics: ['fundamentals'],
  },

  // ── Tools ─────────────────────────────────────────────
  {
    title: 'explainshell.com',
    author: null,
    url: 'https://explainshell.com/',
    description: 'Paste any shell command, get every part explained. Brilliant learning tool.',
    type: 'tool',
    topics: ['fundamentals'],
  },
  {
    title: 'Linux Command Library',
    author: null,
    url: 'https://linuxcommandlibrary.com/',
    description: 'Searchable reference for every terminal command. Works for Mac too.',
    type: 'tool',
    topics: ['fundamentals'],
  },
  {
    title: 'DNS Checker',
    author: null,
    url: 'https://dnschecker.org/',
    description: 'Check DNS propagation across the world in real time.',
    type: 'tool',
    topics: ['deployment'],
  },
  {
    title: 'Loopy',
    author: 'Nicky Case',
    url: 'https://ncase.me/loopy/',
    description: 'Interactive tool for thinking in systems. Draw loops, watch them play out.',
    type: 'tool',
    topics: ['architecture'],
  },
  {
    title: 'Miro',
    author: null,
    url: 'https://miro.com/',
    description: 'Collaborative whiteboard for synthesis, mapping, and brainstorming.',
    type: 'tool',
    topics: ['research'],
  },
  {
    title: 'OptimalSort',
    author: 'Optimal Workshop',
    url: 'https://www.optimalworkshop.com/optimalsort/',
    description: 'Card sorting tool for testing information architecture with real users.',
    type: 'tool',
    topics: ['research'],
  },
  {
    title: 'Netlify Drop',
    author: 'Netlify',
    url: 'https://app.netlify.com/drop',
    description: 'Drag-and-drop instant deployment. Ship a static site in seconds.',
    type: 'tool',
    topics: ['deployment'],
  },
  {
    title: 'Learn Git Branching',
    author: null,
    url: 'https://learngitbranching.js.org/',
    description: 'Interactive Git visualization and practice. See branches come to life.',
    type: 'tool',
    topics: ['fundamentals'],
  },
  {
    title: 'JSON.org',
    author: null,
    url: 'https://www.json.org/',
    description: 'The JSON specification. Short, clear, and the authoritative source.',
    type: 'tool',
    topics: ['architecture'],
  },

  // ── Articles & Guides ─────────────────────────────────
  {
    title: 'Leverage Points: Places to Intervene in a System',
    author: 'Donella Meadows',
    url: 'https://donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system/',
    description: 'Where to push for the biggest systemic change. Foundational systems thinking essay.',
    type: 'article',
    topics: ['architecture'],
  },
  {
    title: "Know Your Customers' Jobs to Be Done",
    author: 'Harvard Business Review',
    url: 'https://hbr.org/2016/09/know-your-customers-jobs-to-be-done',
    description: 'HBR article on the Jobs to Be Done framework. Accessible and practical.',
    type: 'article',
    topics: ['research'],
  },
  {
    title: 'How DNS Works',
    author: null,
    url: 'https://howdns.works/',
    description: 'Visual, step-by-step DNS explainer. Makes the invisible visible.',
    type: 'article',
    topics: ['deployment'],
  },
  {
    title: 'What Is DNS?',
    author: 'Cloudflare',
    url: 'https://www.cloudflare.com/learning/dns/what-is-dns/',
    description: 'Clear, thorough DNS fundamentals from Cloudflare.',
    type: 'article',
    topics: ['deployment'],
  },
  {
    title: 'DNS Zines',
    author: 'Julia Evans',
    url: 'https://wizardzines.com/zines/dns/',
    description: 'Illustrated, joyful DNS concepts. Makes networking feel approachable.',
    type: 'article',
    topics: ['deployment'],
  },
  {
    title: 'The Twelve-Factor App',
    author: 'Heroku',
    url: 'https://12factor.net/',
    description: 'Twelve principles for building modern, portable, scalable web applications.',
    type: 'article',
    topics: ['architecture'],
  },
  {
    title: 'The Feynman Technique',
    author: 'Farnam Street',
    url: 'https://fs.blog/feynman-technique/',
    description: 'Learn anything by teaching it simply. If you cannot explain it, you do not understand it.',
    type: 'article',
    topics: ['craft'],
  },
  {
    title: 'Working Backwards',
    author: 'Werner Vogels (Amazon)',
    url: 'https://www.allthingsdistributed.com/2006/11/working_backwards.html',
    description: 'Start from the customer and work backwards. The Amazon product development method.',
    type: 'article',
    topics: ['process'],
  },
  {
    title: 'The Pomodoro Technique',
    author: 'Francesco Cirillo',
    url: 'https://francescocirillo.com/products/the-pomodoro-technique',
    description: 'Time-boxed focus sessions. Simple, effective, and battle-tested.',
    type: 'article',
    topics: ['process'],
  },
  {
    title: 'Patterns.dev',
    author: 'Lydia Hallie & Addy Osmani',
    url: 'https://www.patterns.dev/',
    description: 'Modern web development and design patterns. Free, visual, well-explained.',
    type: 'article',
    topics: ['web'],
  },
  {
    title: 'Event Storming',
    author: 'Alberto Brandolini',
    url: 'https://www.eventstorming.com/',
    description: 'Collaborative domain modeling with sticky notes. DDD made accessible.',
    type: 'article',
    topics: ['architecture'],
  },
  {
    title: 'Gamestorming',
    author: null,
    url: 'https://gamestorming.com/',
    description: 'Games, exercises, and activities for creative collaboration and ideation.',
    type: 'article',
    topics: ['process'],
  },
  {
    title: 'How to Contribute to Open Source',
    author: 'GitHub',
    url: 'https://opensource.guide/how-to-contribute/',
    description: 'Comprehensive guide to making your first open source contribution.',
    type: 'article',
    topics: ['community'],
  },
  {
    title: 'Building in Public',
    author: 'Kevon Cheung',
    url: 'https://www.buildinpublic.com/',
    description: 'The practice of sharing your building journey. Community and accountability.',
    type: 'article',
    topics: ['community'],
  },
  {
    title: 'The Systems Thinker',
    author: null,
    url: 'https://thesystemsthinker.com/',
    description: 'Articles, resources, and tools for systems thinking practitioners.',
    type: 'article',
    topics: ['architecture'],
  },
  {
    title: 'Code Review Best Practices',
    author: 'Google',
    url: 'https://google.github.io/eng-practices/review/',
    description: "Google's engineering practices for effective code review.",
    type: 'article',
    topics: ['leadership'],
  },
  {
    title: 'Usability Testing 101',
    author: 'Nielsen Norman Group',
    url: 'https://www.nngroup.com/articles/usability-testing-101/',
    description: 'Introduction to usability testing. When, why, and how.',
    type: 'article',
    topics: ['research'],
  },
  {
    title: 'Rapid Prototyping',
    author: 'Nielsen Norman Group',
    url: 'https://www.nngroup.com/articles/rapid-prototyping/',
    description: 'Prototyping techniques and best practices for fast validation.',
    type: 'article',
    topics: ['research'],
  },
  {
    title: 'Which UX Research Methods',
    author: 'Nielsen Norman Group',
    url: 'https://www.nngroup.com/articles/which-ux-research-methods/',
    description: 'Choosing the right research approach for your question.',
    type: 'article',
    topics: ['research'],
  },
  {
    title: 'Information Architecture Articles',
    author: 'Nielsen Norman Group',
    url: 'https://www.nngroup.com/topic/information-architecture/',
    description: 'Curated collection of IA best practices and research.',
    type: 'article',
    topics: ['architecture'],
  },
  {
    title: 'Synthesizing Research',
    author: 'Indi Young',
    url: 'https://indiyoung.com/',
    description: 'Techniques for making sense of qualitative research data.',
    type: 'article',
    topics: ['research'],
  },
  {
    title: 'JTBD.info',
    author: null,
    url: 'https://jtbd.info/',
    description: 'Jobs to Be Done resource hub. Articles, tools, and case studies.',
    type: 'article',
    topics: ['research'],
  },
  {
    title: 'IDEO Design Thinking',
    author: 'IDEO',
    url: 'https://designthinking.ideo.com/',
    description: "IDEO's open design thinking methodology and toolkit.",
    type: 'article',
    topics: ['process'],
  },
  {
    title: 'Reflective Practice',
    author: 'Donald Sch\u00f6n',
    url: 'https://en.wikipedia.org/wiki/Reflective_practice',
    description: 'The concept of the reflective practitioner. Learning by examining your own work.',
    type: 'article',
    topics: ['craft'],
  },
  {
    title: 'Awesome README',
    author: 'GitHub Community',
    url: 'https://github.com/matiassingers/awesome-readme',
    description: 'Curated list of excellent READMEs. Learn documentation by example.',
    type: 'article',
    topics: ['fundamentals'],
  },

  // ── Reference / Documentation ─────────────────────────
  {
    title: 'React Official Tutorial',
    author: 'React Team',
    url: 'https://react.dev/learn',
    description: 'Start here for React. The official interactive tutorial.',
    type: 'reference',
    topics: ['web'],
  },
  {
    title: 'Thinking in React',
    author: 'React Team',
    url: 'https://react.dev/learn/thinking-in-react',
    description: "React's core mental model. How to break a UI into components.",
    type: 'reference',
    topics: ['web'],
  },
  {
    title: 'Describing the UI',
    author: 'React Team',
    url: 'https://react.dev/learn/describing-the-ui',
    description: 'React component patterns and JSX fundamentals.',
    type: 'reference',
    topics: ['web'],
  },
  {
    title: 'Vite Getting Started',
    author: 'Vite Team',
    url: 'https://vite.dev/guide/',
    description: 'Modern build tool setup. Fast, minimal configuration.',
    type: 'reference',
    topics: ['web'],
  },
  {
    title: 'Vite — Deploying a Static Site',
    author: 'Vite Team',
    url: 'https://vite.dev/guide/static-deploy',
    description: 'Deploy options for Vite projects. Netlify, Vercel, GitHub Pages, and more.',
    type: 'reference',
    topics: ['deployment'],
  },
  {
    title: 'Netlify Docs — Get Started',
    author: 'Netlify',
    url: 'https://docs.netlify.com/get-started/',
    description: 'Netlify platform onboarding. From zero to deployed.',
    type: 'reference',
    topics: ['deployment'],
  },
  {
    title: 'Netlify Docs — Custom Domains',
    author: 'Netlify',
    url: 'https://docs.netlify.com/domains-https/custom-domains/',
    description: 'Domain configuration, HTTPS, and DNS setup on Netlify.',
    type: 'reference',
    topics: ['deployment'],
  },
  {
    title: 'Vercel Docs — Deployments',
    author: 'Vercel',
    url: 'https://vercel.com/docs/deployments/overview',
    description: 'Deployment on Vercel. Git integration, preview deploys, serverless functions.',
    type: 'reference',
    topics: ['deployment'],
  },
  {
    title: 'GitHub Pages Docs',
    author: 'GitHub',
    url: 'https://docs.github.com/en/pages',
    description: 'Free static hosting directly from a GitHub repository.',
    type: 'reference',
    topics: ['deployment'],
  },
  {
    title: 'GitHub Git Handbook',
    author: 'GitHub',
    url: 'https://docs.github.com/en/get-started/using-git/about-git',
    description: 'Git basics from GitHub. Clear, beginner-friendly reference.',
    type: 'reference',
    topics: ['fundamentals'],
  },
  {
    title: 'Git Stash Documentation',
    author: 'Git',
    url: 'https://git-scm.com/docs/git-stash',
    description: 'Official reference for git stash. Save work without committing.',
    type: 'reference',
    topics: ['fundamentals'],
  },
  {
    title: 'Claude Code Documentation',
    author: 'Anthropic',
    url: 'https://docs.anthropic.com/en/docs/claude-code/overview',
    description: 'Claude Code overview and reference. The starting point for AI-assisted building.',
    type: 'reference',
    topics: ['ai'],
  },
  {
    title: 'Claude Code Tutorials',
    author: 'Anthropic',
    url: 'https://docs.anthropic.com/en/docs/claude-code/tutorials',
    description: 'Step-by-step guides for Claude Code. Practical walkthroughs.',
    type: 'reference',
    topics: ['ai'],
  },
  {
    title: 'Claude Code Best Practices',
    author: 'Anthropic',
    url: 'https://docs.anthropic.com/en/docs/claude-code/best-practices',
    description: 'Getting the most from Claude Code. Patterns that work.',
    type: 'reference',
    topics: ['ai'],
  },
  {
    title: 'Anthropic Prompt Engineering Guide',
    author: 'Anthropic',
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview',
    description: 'Official prompt engineering documentation. Techniques and strategies.',
    type: 'reference',
    topics: ['ai'],
  },
  {
    title: 'Anthropic Cookbook',
    author: 'Anthropic',
    url: 'https://github.com/anthropics/anthropic-cookbook',
    description: 'Example code and patterns for building with Claude. Open source.',
    type: 'reference',
    topics: ['ai'],
  },
  {
    title: 'MDN: Dealing with Files',
    author: 'Mozilla',
    url: 'https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files',
    description: 'Web file structure basics. How files and folders work for websites.',
    type: 'reference',
    topics: ['web', 'fundamentals'],
  },
  {
    title: 'Prisma Data Modeling Guide',
    author: 'Prisma',
    url: 'https://www.prisma.io/dataguide',
    description: 'Database and data modeling concepts. Clear, modern, well-illustrated.',
    type: 'reference',
    topics: ['architecture'],
  },
  {
    title: 'Indie Hackers',
    author: null,
    url: 'https://www.indiehackers.com/',
    description: 'Community of founders and builders. Stories, forums, and inspiration.',
    type: 'reference',
    topics: ['community'],
  },
];

export default resources;
